### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by lujiazhu** [Triment/efi-hackintosh-chengming3980#1]
您好，请问这个efi可以正常引导吗，是哪个版本的oc呢，我的也是戴尔同型号机器，logo闪一下就黑屏了，加参数跑码也不能停住，貌似只跑了十来行代码，不知道是否bios有需要特殊设置的地方，还请指点一二，多谢啦~

**Comment by Triment** [comment]
https://dortania.github.io/OpenCore-Install-Guide按照官方来设置bios，最新的monterey都可以安装
